#!/opt/homebrew/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_NAME=$(basename "$0")

formulae=$(brew install --dry-run --formulae --quiet $(brew list --formulae) 2>/dev/null | sed -e '1,/==> Would install/d')
casks=$(brew install --dry-run --casks --quiet $(brew list --casks) 2>/dev/null | sed -e '1,/==> Would install/d')

count_formulae=$(echo $formulae | xargs | wc -l | xargs)
count_casks=$(echo $casks | xargs | wc -l | xargs)

count_all=$((count_formulae + count_casks))

icon='iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAw3pUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjabVBBEsMgCLz7ij5BWVR8jmnSmf6gzy8GkolNmXFZWGdFwvZ5v8JjBCUOnKuUVkrU4MaNuhKJFn3HFHlHK9i1NPfDKZC2oBlWSvH7Rz+dBpa6snwxkqcLyyw0f4Dkx4gsYUw0+OpGzY1AJhwTdvtWLE3q9QvLFucQO2EAyzz2ra66vTXrOyDakBAVAbYBMA4CuhJWJFS9mNB2nhUzipvpQv7t6YjwBeOaWR4wr/xNAAABhGlDQ1BJQ0MgcHJvZmlsZQAAeJx9kT1Iw0AcxV8/pCLVDnYQdchQneyiIo61CkWoEGqFVh1MLv2CJg1Jiouj4Fpw8GOx6uDirKuDqyAIfoC4ujgpukiJ/0sKLWI8OO7Hu3uPu3eAv1llqhlMAKpmGZlUUsjlV4XQK4IYQQQhDEjM1OdEMQ3P8XUPH1/v4jzL+9yfo18pmAzwCcQJphsW8QbxzKalc94njrKypBCfE08YdEHiR67LLr9xLjns55lRI5uZJ44SC6UulruYlQ2VeJo4pqga5ftzLiuctzir1Tpr35O/MFzQVpa5TnMUKSxiCSIEyKijgiosxGnVSDGRof2kh3/Y8YvkkslVASPHAmpQITl+8D/43a1ZnJp0k8JJoOfFtj/GgNAu0GrY9vexbbdOgMAzcKV1/LUmMPtJeqOjxY6AyDZwcd3R5D3gcgcYetIlQ3KkAE1/sQi8n9E35YHBW6Bvze2tvY/TByBLXaVvgINDYLxE2ese7+7t7u3fM+3+fgBC53KTOtLOcAAADl5pVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDQuNC4wLUV4aXYyIj4KIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgIHhtbG5zOkdJTVA9Imh0dHA6Ly93d3cuZ2ltcC5vcmcveG1wLyIKICAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIgogICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICB4bXBNTTpEb2N1bWVudElEPSJnaW1wOmRvY2lkOmdpbXA6NDBiMjU3YjktYjMwZi00MGJiLWFjMTAtNzExZmQ5MzRiN2I2IgogICB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjgwNzY3ZDMyLTA5MjAtNDI5Yi04N2RjLWVjMDQ2MDg0MGU4YiIKICAgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOmZhOWQxOTViLTc4ZGYtNDA2YS1hZDkxLWY0OWRmMmJjMDAxOSIKICAgR0lNUDpBUEk9IjIuMCIKICAgR0lNUDpQbGF0Zm9ybT0iTWFjIE9TIgogICBHSU1QOlRpbWVTdGFtcD0iMTY4MjYxNjM1Nzg0OTQ0OSIKICAgR0lNUDpWZXJzaW9uPSIyLjEwLjM0IgogICBkYzpGb3JtYXQ9ImltYWdlL3BuZyIKICAgdGlmZjpPcmllbnRhdGlvbj0iMSIKICAgeG1wOkNyZWF0b3JUb29sPSJHSU1QIDIuMTAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjM6MDQ6MjdUMTk6MjU6NTYrMDI6MDAiCiAgIHhtcDpNb2RpZnlEYXRlPSIyMDIzOjA0OjI3VDE5OjI1OjU2KzAyOjAwIj4KICAgPHhtcE1NOkhpc3Rvcnk+CiAgICA8cmRmOlNlcT4KICAgICA8cmRmOmxpCiAgICAgIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiCiAgICAgIHN0RXZ0OmNoYW5nZWQ9Ii8iCiAgICAgIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MTcxZjkwZmMtODdiNi00ZTYwLTg3OTgtZDkyZDA4Y2Y2YTRiIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJHaW1wIDIuMTAgKE1hYyBPUykiCiAgICAgIHN0RXZ0OndoZW49IjIwMjMtMDQtMjdUMTY6MTg6MDArMDI6MDAiLz4KICAgICA8cmRmOmxpCiAgICAgIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiCiAgICAgIHN0RXZ0OmNoYW5nZWQ9Ii8iCiAgICAgIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MWRiZDc3YjEtZDI4ZC00OWNjLWJjYzUtYmQyOTk1OGRjYzlmIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJHaW1wIDIuMTAgKE1hYyBPUykiCiAgICAgIHN0RXZ0OndoZW49IjIwMjMtMDQtMjdUMTk6MjU6NTcrMDI6MDAiLz4KICAgIDwvcmRmOlNlcT4KICAgPC94bXBNTTpIaXN0b3J5PgogIDwvcmRmOkRlc2NyaXB0aW9uPgogPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgIAo8P3hwYWNrZXQgZW5kPSJ3Ij8+6Zz9KwAAAAZiS0dEAAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB+cEGxEZOWzsH5MAAAHiSURBVDjLtZQ/a1RREMV/5933dlOISmISbcQU4toEUUEEURE/gPgJFAlYxMbPYGEhFhYriIWgKURSCHZ2FmIhFhGNKfxDDIoJpIhGxH0zY+FDdLMbV7JOd+fOPffMuWcu9DnUKVmWZSZpu6TdETEMnJJ0HPgI3I6IuymlTz0BtlqtTSmlBjAJHAZyYAF4DOwAjgA3zaxZFMVK+/n894WZ7Zd0DjgEDEXEdeA58AZ4B4xIugycTykNmtkN4HVKKdZQNbMxd7/v7s/c/ZKZnTWzoTYpcnc/4O5X3H3W3ZtmtrkjQ0njwN6IuCXpGtD6eY/90UVEzETEQpZlo8A+SYPASqeW54FlSQ1gQNIuoNHlMUeqvbcR8bkjw7IsZ1JK05JOAtuA08BFYI0+kmrAakRMA3vMbLEsy/l6vf79F2CtVjN3nwWOVakBYMu6npMmgDPAYlEUU+5+J+9QNxYRE5KO/sXDJfC1st5BwCLiUSfAUUkXgLQeWkQ8iYhJSUnSPWAI2Jp3MXvRw5SVkr5ISoBVBJT1e5b7ARhdR++ffhVpPCKuRoQk7QTmgNV8A8yGJZ2o9FsCHkp6vxHAFxHRrKZrCXiVZdlyO6D3LFzEB+BB+7+YtRXNAS97AP4m6Wll7P8bPwDR78VT5zwRNAAAAABJRU5ErkJggg=='

if [ $# -eq 0 ]; then
    echo " ${count_all} | trim=false | templateImage=${icon}"
    echo "---"
    if [[ "${count_formulae}" != "0" ]]; then
        if [[ "${count_formulae}" == "1" ]]; then
            echo "$count_formulae formula to update"
        else
            echo "$count_formulae formulae to update"
        fi
            for line in $formulae; do 
                echo "$line" | grep "[a-z]" | sed 's_\(.*\)_& | bash=brew param1=install param2=--formula param3=& param4=\&\& param5=exit terminal=true refresh=true_g'
            done
    fi
    if [[ "${count_formulae}" == "0" ]]; then
        echo "No formulae to update"
    fi
    echo "---"
    if [[ "${count_casks}" != "0" ]]; then
        if [[ "${count_casks}" == "1" ]]; then
            echo "$count_casks cask to update"
        else
            echo "$count_casks casks to update"
        fi
            for line in $casks; do 
                echo "$line" | grep "[a-z]" | sed 's_\(.*\)_& | bash=brew param1=install param2=--cask param3=& param4=\&\& param5=exit terminal=true refresh=true_g'
            done
    fi
    if [[ "${count_casks}" == "0" ]]; then
        echo "No casks to update"
    fi
    echo "---"
    echo "Brew Upgrade All | bash=${SCRIPT_DIR}/${SCRIPT_NAME} param1=upgrade param2=&& param3=exit terminal=true refresh=true"
    echo "Brew Cleanup | bash=${SCRIPT_DIR}/${SCRIPT_NAME} param1=cleanup param2=&& param3=exit terminal=true refresh=true"
    echo "---"
    echo "Refresh | refresh=true"
else
    if [[ $1 == 'upgrade' ]]; then
        brew update
        if [[ "${count_formulae}" != "0" ]]; then
            brew upgrade --formulae ${formulae}
        fi
        if [[ "${count_casks}" != "0" ]]; then
            brew upgrade --casks ${casks}
        fi
    fi
    if [[ $1 == 'cleanup' ]]; then
        brew cleanup --formulae
        brew cleanup --casks
    fi
fi
